spec:
  containers:
  - image: paulbouwer/hello-kubernetes:1.10
    name: hello
    env:
      - name: KUBERNETES_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: KUBERNETES_POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: KUBERNETES_NODE_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      - name: CONTAINER_IMAGE
        value: paulbouwer/hello-kubernetes:1.10
    ports:
      - containerPort: 8080
